---

- hosts: localhost
  tasks:
    - include: clean_all.yml
    - name: create VM
      shell:
        source {{ inventory_dir }}/openstack.creds;
        export vm1_name={{ prefix }}_$RANDOM;
        openstack {{ openstack_opts }} server create --flavor {{ _flavor_ }} --image {{ _image_ }} --nic net-id={{ _external_network_ }} \
        --security-group {{ _security_group_ }} --key {{ _key_pair_ }} $vm1_name;
        echo $vm1_name;
        sleep 60;
      args:
        executable: /bin/bash
      register: o_create_vm
    - debug: var=o_create_vm.stdout_lines

    - name: get VMs info
      shell:
        sleep 30;
        source {{ inventory_dir }}/openstack.creds;
        openstack {{ openstack_opts }} server list | grep {{ prefix }};
      args:
        executable: /bin/bash
      register: o_vm_info
    - debug: var=o_vm_info.stdout_lines

    - name: get VM info
      shell:
        sleep 30;
        source {{ inventory_dir }}/openstack.creds;
        openstack {{ openstack_opts }} server show {{ o_create_vm.stdout_lines[-1] }};
      args:
        executable: /bin/bash
      register: o_vm_info
    - debug: var=o_vm_info.stdout_lines

    - name: delete VM
      shell:
        sleep 30;
        source {{ inventory_dir }}/openstack.creds;
        openstack {{ openstack_opts }} server delete {{ o_create_vm.stdout_lines[-1] }};
      args:
        executable: /bin/bash
